### ISSUE TITLE
Client meeting Minutes

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#14]

**Comment by Ninjarku** [comment]
Meeting minutes have been crafted and vetted by our team based on the recorded meeting between the team and client for requirements gathering. Some of the content spoken in the meeting had to be reworded to make sense.
This work does not need to be committed to the repo but is shared with the team.
The work affects the completion deadline as this part will help the team to clear up any misunderstanding on what are the client's requirements.
There are changes to the completion criteria of the task, some functional requirements are added to the list of initial requirements that the team was given, and some of these functional requirements were modified after the meeting with the client.
The Start date was right after the client meeting on 7 September 2023 and the end date of the work done for this comment was 8 September 2023.

**Comment by Ninjarku** [comment]
Meeting minutes have been crafted and vetted by our team based on the recorded meeting between the team and client for requirements gathering. Some of the content spoken in the meeting had to be reworded to make sense.
This work does not need to be committed to the repo but is shared with the team.
The work affects the completion deadline as this part will help the team to clear up any misunderstanding on what are the client's requirements.
There are changes to the completion criteria of the task, some functional requirements are added to the list of initial requirements that the team was given, and some of these functional requirements were modified after the meeting with the client.
The Start date was right after the client meeting on 7 September 2023 and the end date of the work done for this comment was 8 September 2023.
