### ISSUE TITLE
1.2.1 Create Team Repository

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#22]

**Comment by Ik0nw** [comment]
Task 1.2.1
Task Description: Create team Repository
Goals: Create team Repository
Successful Criteria: Create team Repository
Allocated Time: 1 Day
Start and End Date of the Task: 31/8/23 - 31/8/23
Person In-Charge: Chen xing
Status of Task: Completed
Priority: High

**Comment by Ik0nw** [comment]
Task 1.2.1
Task Description: Create team repository
Goals:Create team repository
Successful Criteria: Create team repository
Allocated Time: 1 Day
Start and End Date of the Task: 31/8/23 - 31/8/23
Person In-Charge: Chen Xing
Status of Task: Completed
Priority: High

**Comment by Ik0nw** [comment]
Work Description: Create team repository
Committed to Repository: N.A
Changes to Completion Deadline: No.
Changes to Completion Criteria: No
Start and End Date of this Comment: 31/8/23 - 31/8/23
