### ISSUE TITLE
1.3 Create Team Slack

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#23]

**Comment by Ik0nw** [comment]
Task 1.3
Task Description: Create team slack
Goals: Create team slack
Successful Criteria: Create team slack
Allocated Time: 1 Day
Start and End Date of the Task: 31/8/23 - 31/8/23
Person In-Charge: Chen Xing
Status of Task: Completed
Priority: High

**Comment by Ik0nw** [comment]
Work Description: Create Team Slack
Committed to Repository: N.A
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 31/8/23 - 31/8/23
