### ISSUE TITLE
1.5.1 Compile Questions for Client (Mr David Cheng)

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#24]
Task 1.5.1
Task Description: Compile questions require for the client
Goals: Ascertain the requirements needed from the client
Successful Criteria: Completion of minutes
Allocated Time: 1 day
Start and End Date of the Task: 4/9/23 - 4/9/23
Person In-Charge: Nikhil
Status of Task: Completed
Priority: High

**Comment by KR0N0S99** [comment]
Work Description: Compilation of Questions needed to elicit answers from the client
Committed to Repository: N.A
Changes to Completion Deadline: No.
Changes to Completion Criteria: No
Start and End Date of this Comment: 16/9/2023 - 16/9/2023
