### ISSUE TITLE
1.2.2 Create Team Wiki

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#25]

**Comment by Ik0nw** [comment]
Task 1.2.2
Task Description: Create Team Wiki
Goals: Create a github wiki repo for team
Successful Criteria: Create a github wiki repo for team
Allocated Time: 1 Days
Start and End Date of the Task: 31/8/23 - 31/8/23
Person In-Charge: Chen Xing
Status of Task: Completed
Priority: High

**Comment by Ik0nw** [comment]
Work Description: Create Team Wiki
Committed to Repository: N.A
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 31/8/23 - 31/8/23
