### ISSUE TITLE
1.5.4 Send Meeting Minutes to Client

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#28]
Task 1.5.4
Task Description: Send meeting minutes to the client
Goals: Let the client know how we documented our minutes
Successful Criteria: Client acknowledges and approves of our work
Allocated Time: 1 day
Start and End Date of the Task: 9/9/23 - 9/9/23
Person In-Charge: Nikhil
Status of Task: Completed
Priority: High

**Comment by KR0N0S99** [comment]
Work Description: Send the client an email containing our meeting minutes for approval
Committed to Repository: N.A
Changes to Completion Deadline: No.
Changes to Completion Criteria: No
Start and End Date of this Comment: 16/9/2023 - 16/9/2023
