### ISSUE TITLE
1.6 Generate Functional Requirements

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#29]
Task #29
Task Description: Generate Functional Requirements based on initial requirements set out by the document and client meeting.
Goals: Have fully valid functional requirements that are not vague, but clear, in order to help us create the product.
Completion Criteria: All requirements from the document and client meeting are written down as functional requirements.
Allocated Time: 7 days
Start Date of the Task: 10/09/2023
End Date of the Task: 17/09/2023
Person In-Charge: Aloysius
Status of Task: In-progress
Priority: High Priority

**Comment by aleukh** [comment]
Work Description: Generated a few functional requirements and wrote them onto the M1 report. Functional requirements in the report consists of initial requirements and new updated information from client meeting and email. As of this comment, we have generated a total of 29 functional requirements.
Committed to Repository: NIL
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start End Date of this comment: 10/09/2023
End Date of this Comment: 13/09/2023

**Comment by aleukh** [comment]
Work Description: Read through all the functional requirements and removed certain functional requirements. Currently at 28 functional requirements.
Committed to Repository: NIL
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 16/09/2023 - 17/09/2023
