### ISSUE TITLE
1.3.2 Generate Non-Functional Requirements

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#30]
Task 1.7
Task Description: Create Non-Functional Requirements
Goals: Create valid NFR's
Successful Criteria: NFR's align with our project goals
Allocated Time: 3 day
Start and End Date of the Task: 10/9/23 - 14/9/23
Person In-Charge: Nikhil
Status of Task: In-Progress
Priority: High

**Comment by KR0N0S99** [comment]
Task 1.5.4
Task Description: Send meeting minutes to the client
Goals: Let the client know how we documented our minutes
Successful Criteria: Client acknowledges and approves of our work
Allocated Time: 1 day
Start and End Date of the Task: 9/9/23 - 9/9/23
Person In-Charge: Nikhil
Status of Task: Completed
Priority: High

**Comment by KR0N0S99** [comment]
Work Description: Finish creation of Non Functional Requirements
Committed to Repository: N.A
Changes to Completion Deadline: No.
Changes to Completion Criteria: No
Start and End Date of this Comment: 20/9/2023 - 20/9/2023
