### ISSUE TITLE
1.4.1 Create Use Case Diagram

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#31]
Task 1.4.1
Task Description: Create Use Case Diagram
Goals: Create valid UCD
Successful Criteria: UCD align with our project goals
Allocated Time: 7 day
Start and End Date of the Task: 9/9/23 - 15/9/23
Person In-Charge: Nikhil
Status of Task: Completed
Priority: High

**Comment by KR0N0S99** [comment]
Work Description: Finish creation of Use Case Diagram
Committed to Repository: N.A
Changes to Completion Deadline: No.
Changes to Completion Criteria: No
Start and End Date of this Comment: 21/9/2023 - 21/9/2023
