### ISSUE TITLE
1.8.2 Write Use Case Description

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#32]

**Comment by cuty101** [comment]
Task 1.8.2
Task Description: Write a use case description
Goals: Write up a use case description for each of the use cases
Completion Criteria: All use case diagrams have a use case description
Allocated Time: 
Start and End Date of the Task: 
Person In-Charge: Jia Ye
Status of Task: To-Do
Priority: High

**Comment by cuty101** [comment]
Work Description: Write a use case description
Committed to Repository: 20/9/23
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 13/9/23 - 20/9/23
