### ISSUE TITLE
1.11 Prepare Report for M1 Submission

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#34]

**Comment by cuty101** [comment]
Task 1.11
Task Description: Prepare Report for M1  Submission
Goals: Come up with the report before the M1 submission deadline
Completion Criteria: All criteria of the M1 report met
Allocated Time: 1 Week
Start and End Date of the Task: 13/9/23 - 20/9/23
Person In-Charge: Jia Ye
Status of Task: To-Do
Priority: High

**Comment by cuty101** [comment]
Work Description: Prepare Report for M1 Submission
Committed to Repository: 21/9/23
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 16/9/23 - 21/9/23
