### ISSUE TITLE
Interview Client

### ISSUE THREAD

**Issue by aleukh** [Ik0nw/INF2001-P9-2-WIKI#4]
Task ID 4

Interview Client on 7/9/2023 at MR6A
The goals of this task is to meet client and gather requirements
Successful criteria: Gather all requirements
Allocated Time: 15 minutes
Start date: 7/9/2023
End date: 7/9/2023
Person-in-Charge: Aloysius
Status: Completed as of 7/9/2023
Priority: High priority

**Comment by aleukh** [comment]
Met the client on 7/9/2023 at MR6a to discuss and gather more insights to the requirements for the project.

The agenda for the meeting have been captured in the meeting minutes.

The work done have not affected the completion deadline.

No changes to the success criteria.

Start Date of task: 07/09/2023
End Date of task: 07/09/2023

**Comment by Bread7** [comment]
test
