### ISSUE TITLE
1.6.2 Review Report & M1 Submission

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#40]
Task 1.6.2
Task Description:
Perform a final vetting on the report and submit the project M1 report.
Goals:
To complete the project report for vetting and submit it once vetted.
Completion Criteria:
The M1 project report is filled out completely.
The M1 project report is submitted on XSite Dropbox.

Allocated Time: # Week(s) # Day(s)
Start and End Date of the Task: 21/09/2023 - 23/09/2023
Person In-Charge: Beckham
Status of Task: In-Progress
Priority: Medium

**Comment by Ninjarku** [comment]
Work Description:
M1 Project report completed, vetted and submitted.

Committed to Repository:
This work does not need to be committed to the repo.

Changes to Completion Deadline: (explain if yes)
There are no changes.

Changes to Completion Criteria: (explain if yes)
There are no changes.

Start and End Date of this Comment:
The Start date was on 21 September 2023 and the end date of the work done for this comment was 23 September 2023.
