### ISSUE TITLE
2.1.2 Component Diagram

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#43]

**Comment by Ik0nw** [comment]
Task 2.1.2
Task Description: Draw a Component Diagram
Goals: Create a Component Diagram
Completion Criteria: Create a Component Diagram
Allocated Time: 1 Week
Start and End Date of the Task: 17/10/23 - 24/10/23
Person In-Charge: Chen Xing
Status of Task: Completed
Priority: High

**Comment by Ik0nw** [comment]
Work Description: Draw a Component Diagram
Committed to Repository: 24/10/23
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 17/10/23 - 24/10/23
