### ISSUE TITLE
2.2.2 Class Diagram

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#45]
Task 2.2.2
Task Description: Create Class Diagram
Goals: Create valid Class Diagram
Successful Criteria: Class Diagram should align with project goals
Allocated Time: 7 days
Start and End Date of the Task: 16/10/23 - 23/10/23
Person In-Charge: Nikhil
Status of Task: Completed
Priority: High

**Comment by KR0N0S99** [comment]
Work Description: Create Class Diagram
Committed to Repository: N.A
Changes to Completion Deadline: No.
Changes to Completion Criteria: No
Start and End Date of this Comment: 24/10/2023 - 24/10/2023
