### ISSUE TITLE
2.2.3 Sequence Diagram

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#46]

**Comment by cuty101** [comment]
Task 2.2.3
Task Description: Sequence Diagram
Goals: Draw out the sequence diagram
Completion Criteria: Sequence diagram meets the system requirements
Allocated Time: 5 days
Start and End Date of the Task: 16/10/23 - 20/10/23
Person In-Charge: Jia Ye
Status of Task: Completed
Priority: High

**Comment by cuty101** [comment]
Work Description: Sequence Diagram
Committed to Repository: 20/10/23
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 16/10/23 - 20/10/23
