### ISSUE TITLE
2.6 Project M2 Presentation

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#49]
Task 2.6
Task Description: Project M2 Presentation to show work done to Client
Goals: Showcase Class diagram, Sequence Diagrams and Component Diagram to Client.
Successful Criteria: Client acknowledges and approves of our work
Allocated Time: 1 days
Start and End Date of the Task: 2/11/23 - 2/11/23
Person In-Charge: Beckham
Status of Task: Completed
Priority: Medium

**Comment by Ninjarku** [comment]
Work Description:
Presentation was shown to lecturer and feedbacks were provided

Committed to Repository:
This work does not need to be committed to the repo.

Changes to Completion Deadline: (explain if yes)
There are no changes.

Changes to Completion Criteria: (explain if yes)
There are no changes.

Start and End Date of this Comment:
The Start date was on 2 November 2023 and the end date of the work done for this comment was 2 November 2023.
