### ISSUE TITLE
2.5 Review Report & M2 Submission

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#50]
Task 2.5
Task Description: Review overall reports and check to ensure diagrams are accurate.
Goals: Ensure that report is in line with requirements and ensure diagrams are created accurately.
Successful Criteria: Report in line with requirements and diagrams are accurate.
Allocated Time: 3 days
Start and End Date of the Task: 26/10/23 - 28/10/23
Person In-Charge: Aloysius
Status of Task: In-Progress
Priority: Medium

**Comment by aleukh** [comment]
Work Description: Met in class to discuss about the report and to make sure the diagrams are accurate.
Committed to Repository: NIL
Changes to Completion Deadline: The work done have not affected the completion deadline.
Changes to Completion Criteria: No changes to the success criteria.
Start Date of Task: 26/10/2023
End Date of Task: 26/10/2023
