### ISSUE TITLE
3.2 Blackbox Testing

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#52]

**Comment by cuty101** [comment]
Task 3.2
Task Description: Black Box Testing
Goals: Ensure the reduction of bugs as much as possible
Completion Criteria: Output of system matches expected outputs
Allocated Time: 4 Days
Start and End Date of the Task: 7/11/23 - 10/11/23
Person-In-Charge: Jia Ye
Status of Task: Completed
Priority: High

**Comment by cuty101** [comment]
Work Description: Black Box Testing
Committed to Repository: 22/11/23
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 7/11/23 - 10/11/23
