### ISSUE TITLE
3.3 Whitebox Testing

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#53]
Task 3.3
Work Description:
Whitebox test the project, with knowledge of the codes used in the process for the project, for verification and validation. 
Goals:
To check for any errors and bugs in the project.
Successful Criteria: Basic functionality is achieved in the testing to be functional, all bugs found in the project have been reported to the development team.
Allocated Time: 5 days
Start and End Date of the Task: 11/11/23 - 15/11/23
Person In-Charge: Beckham
Status of Task: Backlog
Priority: High

**Comment by Ninjarku** [comment]
Work Description: Check for any errors and bugs in the project.
Committed to Repository: NIL
Changes to Completion Deadline: The work done have not affected the completion deadline.
Changes to Completion Criteria: No changes to the success criteria.
Start Date of Task: 11/11/2023
End Date of Task: 15/11/2023
