### ISSUE TITLE
3.4 Software Configuration

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#54]

**Comment by Ik0nw** [comment]
Task 3.4
Work Description:
Software Configuration
Goals:
Software COnfiguration
Allocated Time: 5 days
Start and End Date of the Task: 16/11/23 - 21/11/23
Person In-Charge: Chen Xing
Status of Task: Backlog
Priority: High

**Comment by Ik0nw** [comment]
Work Description: Software Configuration
Committed to Repository: NIL
Changes to Completion Deadline: The work done have not affected the completion deadline.
Changes to Completion Criteria: No changes to the success criteria.
Start Date of Task: 16/11/2023
End Date of Task: 21/11/2023
