### ISSUE TITLE
3.6 M3 Submission

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#55]

**Comment by cuty101** [comment]
Task 3.6
Task Description: M3 Submission
Goals: Submit M3
Completion Criteria: Everything is ready for M3
Allocated Time: 1 Days
Start and End Date of the Task: 26/11/23 - 26/11/23
Person-In-Charge: Jia Ye
Status of Task: Completed
Priority: High

**Comment by cuty101** [comment]
Work Description: M3 Submission
Committed to Repository: 24/11/23
Changes to Completion Deadline: Yes, brought forward to the 24th
Changes to Completion Criteria: No
Start and End Date of this Comment: 24/11/23 - 24/11/23
