### ISSUE TITLE
3.5 Update Architectural Design

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#56]
Task 3.5
Task Description: Choose and update the architectural design pattern of the system.
Goals: Select the architectural design pattern that best fits our system.
Completion Criteria: The architectural design pattern has been selected and is suitable for our system.
Allocated Time: 5 days
Start Date of the Task: 21/11/2023
End Date of the Task: 25/11/2023
Person In-Charge: Aloysius
Status of Task: In-progress
Priority: High Priority

**Comment by aleukh** [comment]
Work Description: Met with the team to discuss the appropriate architectural design pattern for our system.
Committed to Repository: NIL
Changes to Completion Deadline: The work done have not affected the completion deadline.
Changes to Completion Criteria: No changes to the success criteria.
Start Date of Task: 21/11/2023
End Date of Task: 25/11/2023
