### ISSUE TITLE
3.6.1 Review Report & M3 Submission

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#57]
Task 3.6.1
Task Description: Review Report and M3 submission
Goals: Properly review the report content for M3 submission
Successful Criteria: Report should contain all information required for the submission
Allocated Time: 7 days
Start and End Date of the Task: 16/11/23 - 23/11/23
Person In-Charge: Nikhil
Status of Task: Completed
Priority: High

**Comment by KR0N0S99** [comment]
Work Description: Review Report and M3 submission
Committed to Repository: N.A
Changes to Completion Deadline: No.
Changes to Completion Criteria: No
Start and End Date of this Comment: 23/11/2023 - 23/11/2023
