### ISSUE TITLE
3.6.2 Project M3 Presentation

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#58]
Task 3.6.2
Task Description: Present our M3 presentation.
Goals: Successfully present our M3, which is a video walkthrough of our prototype wireframe.
Completion Criteria: Record and edit the video successfully.
Allocated Time: 2 days
Start Date of the Task: 22/11/2023
End Date of the Task: 23/11/2023
Person In-Charge: Aloysius
Status of Task: In-progress
Priority: High Priority

**Comment by aleukh** [comment]
Work Description: Recorded the prototype wireframe walkthrough, and edited the video.
Committed to Repository: NIL
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 22/11/2023 - 23/11/2023
