### ISSUE TITLE
1.1 Project Initialisation

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#60]
Task 1.1
Task Description:
Ensure the creation of Project Charter, Project Repository, Team Wiki, Team Slack, and Analyse Initial Requirements.
Goals: To have a record of the meeting to inform all parties involved in the project
Successful Criteria: Completion of minutes
Allocated Time: 3 days
Start and End Date of the Task: 31/8/23 - 2/9/23
Person In-Charge: Beckham
Status of Task: Completed
Priority: High

**Comment by Ninjarku** [comment]
Work Description:
The Project Charter and Team Wiki have been created and filled, and our Project Repository and Team Slack have been created with the team members. Used the project description provided to Analyse the Initial Requirements.

Committed to Repository:
The Team Wiki was committed.

Changes to Completion Deadline: (explain if yes)
There are no changes.

Changes to Completion Criteria: (explain if yes)
There are no changes.

Start and End Date of this Comment:
The Start date was on 31 August 2023 and the end date was 2 September 2023.
