### ISSUE TITLE
1.2 Client Meeting Details

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#61]
Task 1.2
Task Description: Overview of Client Meeting Details.
Goals: Meet client and gather requirements.
Completion Criteria: All subsections of 1.2 completed.
Allocated Time: 6 Days
Start and End Date of the Task: 04/09/2023 - 09/09/2023
Person In-Charge: Aloysius
Status of Task: On-going
Priority: High priority

**Comment by aleukh** [comment]
Work Description: Work done on subsections.
Committed to Repository: NIL
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 04/09/2023 - 09/09/2023
