### ISSUE TITLE
1.3 Generate Requirements

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#62]
Task 1.3
Task Description: Overview of the generation of Functional Requirements and Non-functional Requirements
Goals: Completely generate Functional Requirements and Non-functional Requirements
Completion Criteria: Completion of 1.3 subsections.
Allocated Time: 1 Week 1 Day
Start and End Date of the Task: 10/09/2023 - 17/09/2023
Person In-Charge: Aloysius
Status of Task: In-progress
Priority: High priority

**Comment by aleukh** [comment]
Work Description: Work done on subsections.
Committed to Repository: NIL
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 10/09/2023 - 17/09/2023
