### ISSUE TITLE
1.5 System Architecture

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#64]

**Comment by cuty101** [comment]
Task 1.5
Task Description: System Architecture
Goals: Complete the System Architectures and all subtasks
Completion Criteria: All subtasks of 1.5 completed
Allocated Time: 1 Week
Start and End Date of the Task: 13/09/2023 - 19/09/2023
Person In-Charge: Jia Ye
Status of Task: Completed
Priority: High

**Comment by cuty101** [comment]
Work Description: System Architecture
Committed to Repository: 19/09/2023
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 13/09/2023 - 19/09/2023
