### ISSUE TITLE
1.6 M1 Submission

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#65]
Task 1.6
Task Description: 
Ensure the Completion, Vetting and submission of the M1 report.
Goals: 
To enforce the completion of M1 report.
Successful Criteria: Completion of M1 Report
Allocated Time: 13 days
Start and End Date of the Task: 16/9/23 - 28/9/23
Person In-Charge: Beckham
Status of Task: In-progress
Priority: Normal

**Comment by Ninjarku** [comment]
Work Description:
M1 Project report fully completed, vetted and submitted. The presentation had been completed as well for M1 and feedback was received.

Committed to Repository:
This work does not need to be committed to the repo.

Changes to Completion Deadline: (explain if yes)
There are no changes.

Changes to Completion Criteria: (explain if yes)
There are no changes.

Start and End Date of this Comment:
The Start date was on 16 September 2023 and the end date of the work done for this comment was 28 September 2023.
