### ISSUE TITLE
M1 What can be improved?

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#66]

**Comment by Bread7** [comment]
Internally we have good communication, perhaps more detailed specification of tasks during meetings can cut down meeting time and further improve work efficiency

**Comment by Ik0nw** [comment]
We need to be more aware of specific details, and also planned a well agenda before meeting to be more progressive

**Comment by cuty101** [comment]
Meeting time can be more fixed

**Comment by aleukh** [comment]
Meetings could have a planned agenda in order for meetings to more more smoothly

**Comment by KR0N0S99** [comment]
Having an agenda before a digital meeting helps. Tasks can have more specifics given to them

**Comment by Ninjarku** [comment]
Meetings can have a better sense of direction at the beginning if agenda was created at the beginning.
