### ISSUE TITLE
M1 What goes well?

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#67]

**Comment by Bread7** [comment]
Good active communication to get work done efficiently

**Comment by cuty101** [comment]
Good team dynamics. Transparency among teammates. Regular meetings held to clear misunderstandings

**Comment by KR0N0S99** [comment]
Team dynamics are very good. We can bounce ideas off of each other and receive useful critique. There is a good level of transparency among us.

**Comment by aleukh** [comment]
Good levels of transparency and team dynamics. Everyone contributed to get work done efficiently and in a timely manner.

**Comment by Ik0nw** [comment]
Good team dynamic.

**Comment by Ninjarku** [comment]
The team dynamics was good with rather fluid communication. The meetings were generally productive with a good final decision after the meetings.
