### ISSUE TITLE
2.2 UML Diagrams

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#68]
Task 2.2
Task Description: Create UML Diagrams including Class Diagram, Component Diagram and Sequence Diagram
Goals: Create valid UML Diagrams
Successful Criteria: UML Diagram should align with project goals
Allocated Time: 9 days
Start and End Date of the Task: 16/10/23 - 24/10/23
Person In-Charge: Aloysius
Status of Task: Completed
Priority: High

**Comment by aleukh** [comment]
Work Description: Create UML Diagrams including Class Diagram, Component Diagram and Sequence Diagram
Committed to Repository: N.A
Changes to Completion Deadline: No.
Changes to Completion Criteria: No
Start and End Date of this Comment: 24/10/2023 - 24/10/2023
