### ISSUE TITLE
2.1.3 Review Use Case Description

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#75]
Task 2.1.3
Task Description:
Reviewing of the updated Use Case Description.
Goals:
To ensure the changes to the Use Case Description are valid and follow the feedback provided in Milestone 1.
Successful Criteria: Reviewed Use Case Description to be accurate.
Allocated Time: 1 day
Start and End Date of the Task: 20/10/23 - 21/10/23
Person In-Charge: Beckham
Status of Task: Completed
Priority: Medium

**Comment by Ninjarku** [comment]
Work Description:
Project Use Case Descriptions vetting and reviewing according to the feedback provided in Milestone 1.

Committed to Repository:
This work does not need to be committed to the repo.

Changes to Completion Deadline: (explain if yes)
There are no changes.

Changes to Completion Criteria: (explain if yes)
There are no changes.

Start and End Date of this Comment:
The Start date was on 20 October 2023 and the end date of the work done for this comment was 21 October 2023.
