### ISSUE TITLE
2.1.4 Review Use Case Diagram

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#76]

**Comment by cuty101** [comment]
Task 2.1.4
Task Description: Review Use Case Diagram
Goals: Review the Use Case Diagram
Completion Criteria: No further corrections required
Allocated Time: 2 Days
Start and End Date of the Task: 21/10/23 - 22/10/23
Person In-Charge: Jia Ye
Status of Task: Completed
Priority: High

**Comment by cuty101** [comment]
Work Description: Review Use Case Diagram
Committed to Repository: 22/10/23
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 21/10/23 - 22/10/23
