### ISSUE TITLE
2.2.4 Review Component Diagram

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#77]
Task 2.2.4
Task Description: Review the component diagram and ensure that it is accurate.
Goals: Ensure that the component diagram makes sense and tallies with the class diagram.
Successful Criteria: Component Diagram makes sense and is in line with class diagram.
Allocated Time: 11 days
Start and End Date of the Task: 16/10/23 - 26/10/23
Person In-Charge: Aloysius
Status of Task: In-Progress
Priority: Medium

**Comment by aleukh** [comment]
Work Description: Review component diagrams and compare previous revisions of the diagram to select the most accurate one.
Committed to Repository: N.A
Changes to Completion Deadline: No.
Changes to Completion Criteria: No
Start and End Date of this Comment: 26/10/2023 - 26/10/2023
