### ISSUE TITLE
2.2.5 Review Class Diagram

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#78]
Task 2.2.5
Task Description: Reviewed Class Diagram 
Goals: Reviewed class diagram and updated it
Successful Criteria: Successfully reviewed diagram
Allocated Time: 7 days
Start and End Date of the Task: 17/10/23 - 24/10/23
Person In-Charge: Nikhil
Status of Task: Completed
Priority: High

**Comment by KR0N0S99** [comment]
Work Description: Review Class Diagram
Committed to Repository: N.A
Changes to Completion Deadline: No.
Changes to Completion Criteria: No
Start and End Date of this Comment: 26/10/2023 - 26/10/2023
