### ISSUE TITLE
2.3.1 Research Software Design

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#80]
Task 2.3.1
Task Description:
Research on the Software Design of the project regarding waht can be used for the software design of the project.
Goals:
To ensure have ample knowledge regarding Software Desgin of the project for accurate and suitable Software Design creation.
Successful Criteria: Software Design knowledge is well researched and understood by the team.
Allocated Time: 3 days
Start and End Date of the Task: 18/10/23 - 20/10/23
Person In-Charge: Beckham
Status of Task: Completed
Priority: Medium

**Comment by Ninjarku** [comment]
Work Description:
Research on the Software Design of the project regarding waht can be used for the software design of the project.

Committed to Repository:
This work does not need to be committed to the repo.

Changes to Completion Deadline: (explain if yes)
There are no changes.

Changes to Completion Criteria: (explain if yes)
There are no changes.

Start and End Date of this Comment:
The Start date was on 18 October 2023 and the end date of the work done for this comment was 20 October 2023.
