### ISSUE TITLE
2.3.3 Software Design Approval

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#82]
Task 2.3.3
Task Description: Get approval for our software designs from our professors and clear up any misunderstandings regarding software design.
Goals: Get green light on our selected software design and have diagrams that correspond to the selected software design.
Successful Criteria: UML Diagrams are to be in line with the selected software designs.
Allocated Time: 5 days
Start and End Date of the Task: 20/10/23 - 24/10/23
Person In-Charge: Aloysius
Status of Task: Completed
Priority: High

**Comment by aleukh** [comment]
Work Description: Selected our software design and gotten approval from the professors.
Committed to Repository: N.A
Changes to Completion Deadline: No.
Changes to Completion Criteria: No
Start and End Date of this Comment: 24/10/2023 - 24/10/2023
