### ISSUE TITLE
2.4.1 Academic Research

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#83]
Task 2.2.2
Task Description: Do research on articles
Goals: Get valuable information from articles
Successful Criteria: Academic research aids with report and diagrams
Allocated Time: 7 days
Start and End Date of the Task: 16/10/23 - 22/10/23
Person In-Charge: Nikhil
Status of Task: Completed
Priority: High

**Comment by KR0N0S99** [comment]
Work Description: Done research on articles
Committed to Repository: N.A
Changes to Completion Deadline: No.
Changes to Completion Criteria: No
Start and End Date of this Comment: 26/10/2023 - 26/10/2023
