### ISSUE TITLE
3.1.1 Prototype Creation

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#85]

**Comment by cuty101** [comment]
Task 3.1.1
Task Description: Prototype Creation
Goals: Create a working prototype for testing
Completion Criteria: Working and ready for testing
Allocated Time: 4 Days
Start and End Date of the Task: 7/11/23 - 10/11/23
Person In-Charge: Jia Ye
Status of Task: Completed
Priority: High

**Comment by cuty101** [comment]
Work Description: Prototype Creation
Committed to Repository: 19/11/23
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 7/11/23 - 9/11/23
