### ISSUE TITLE
3.1.2 Prototype Review

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#86]
Task 3.1.2
Work Description:
Review the prototype created and check if functional requirements are met for the prototype.
Goals:
Ensure that the prototype meets all functional requirements provided by the clients.
Allocated Time: 1 day
Start and End Date of the Task: 7/11/23 - 7/11/23
Person In-Charge: Beckham
Status of Task: Backlog
Priority: Medium

**Comment by Ninjarku** [comment]
Work Description:
Prototype has been review and passed the checks for user requirements

Committed to Repository:
This work does not need to be committed to the repo.

Changes to Completion Deadline: (explain if yes)
There are no changes.

Changes to Completion Criteria: (explain if yes)
There are no changes.

Start and End Date of this Comment:
The Start date was on 7 November 2023 and the end date of the work done for this comment was 7 November 2023.
