### ISSUE TITLE
3.2.2 Blackbox Testing Review

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#88]

**Comment by Ik0nw** [comment]
Task 3.2.2
Task Description: BlackBox Testing Review
Goals: Finish BlackBox Testing Review
Successful Criteria: Finish BlackBox Testing Review
Allocated Time: 1 day
Start and End Date of the Task: 10/11/23 - 10/11/23
Person In-Charge: Chen Xing
Status of Task: In-Progress
Priority: High

**Comment by Ik0nw** [comment]
Work Description: Finish BlackBox Testing Review
Committed to Repository: -
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 10/11/23 - 10/11/23
