### ISSUE TITLE
3.3.1 Whitebox Testing Plan

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#89]
Task 3.3.1
Task Description: Select the appropriate white box testing method, while providing the pseudocode for our functions and creating the Control Flow Graph.
Goals: The appropriate white box testing method should be selected, and the Control Flow Graph should be accurate with its accompanying cyclomatic complexity calculations.
Completion Criteria: Selected suitable white box testing method with accurate Control Flow Graph and cyclomatic complexity calculations.
Allocated Time: 5 days
Start Date of the Task: 11/11/2023
End Date of the Task: 15/11/2023
Person In-Charge: Aloysius
Status of Task: In-progress
Priority: High Priority

**Comment by aleukh** [comment]
Work Description: Met up with the team to discuss which white box testing method to choose for our system. We generated the pseudocode and created the Control Flow Graph, as well as calculating the cyclomatic complexity.
Committed to Repository: NIL
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 11/11/2023 - 15/11/2023
