### ISSUE TITLE
3.3.2 Whitebox Testing Review

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#90]

**Comment by cuty101** [comment]
Task 3.3.2
Task Description: White Box Testing Review
Goals: Ensure the reduction of bugs as much as possible
Completion Criteria: Everything in the white box testing plan is covered
Allocated Time: 1 Days
Start and End Date of the Task: 15/11/23 - 15/11/23
Person-In-Charge: Jia Ye
Status of Task: Completed
Priority: High

**Comment by cuty101** [comment]
Work Description: Black Box Testing
Committed to Repository: 22/11/23
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 15/11/23 - 15/11/23
