### ISSUE TITLE
3.4.1 Software Configuration Plan

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#91]

**Comment by cuty101** [comment]
Task 3.4.1
Task Description: Software Configuration Plan
Goals: Ensure the reduction of bugs as much as possible
Completion Criteria: Everything in the white box testing plan is covered
Allocated Time: 1 Days
Start and End Date of the Task: 15/11/23 - 15/11/23
Person-In-Charge: Jia Ye
Status of Task: Completed
Priority: High

**Comment by cuty101** [comment]
Work Description: Software Configuration Plan
Committed to Repository: 22/11/23
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 16/11/23 - 20/11/23
