### ISSUE TITLE
3.5.1 Architectural Design Edit

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#93]
Task 3.5.1
Task Description: Architectural Design Editing
Goals: Create and edit Architectural design component
Successful Criteria: Architecture design should align with project goals
Allocated Time: 6 days
Start and End Date of the Task: 2/11/23 - 8/11/23
Person In-Charge: Nikhil
Status of Task: Completed
Priority: High

**Comment by KR0N0S99** [comment]
Work Description: Created and made edits to the Architectural design component
Committed to Repository: N.A
Changes to Completion Deadline: No.
Changes to Completion Criteria: No
Start and End Date of this Comment: 8/11/2023 - 8/11/2023
