### ISSUE TITLE
3.5.2 Architectural Design Review

### ISSUE THREAD

**Issue by Bread7** [Ik0nw/INF2001-P9-2-WIKI#94]

**Comment by Ik0nw** [comment]
Task 3.5.2
Task Description: Architectural Design Review
Goals: Finish Architectural Design Review
Successful Criteria: Finish Architectural Design Review
Allocated Time: 3 day
Start and End Date of the Task: 22/11/23 - 24/11/23
Person In-Charge: Chen Xing
Status of Task: In-Progress
Priority: High

**Comment by Ik0nw** [comment]
Work Description: Architectural Design Review
Committed to Repository: -
Changes to Completion Deadline: No
Changes to Completion Criteria: No
Start and End Date of this Comment: 22/11/23 - 24/11/23
